# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarConnection'
        organization: 'mysonarcloudorganizationkeys'
        scannerMode: 'MSBuild'
        projectKey: 'mysonarcloudorganizationkeys'
        projectName: 'APICoreSonarScanProject'
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      displayName: Restore Nuget Packages
      inputs:
        restoreSolution: '$(solution)' 

    - task: UseDotNet@2
      displayName: NET 6.0
      inputs:
        packageType: 'sdk'
        version: '6.0.x'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '**/*.sln'
        arguments: '--no-incremental -c Release'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: |
          **\*Test.csproj
          **\*Tests.csproj
        arguments: --collect "Code Coverage"
        
    - task: SonarCloudAnalyze@1
      displayName: 'Run Code Analysis'
      inputs:
        jdkversion: 'JAVA_HOME_11_X64'

    - task: SonarCloudPublish@1
      displayName: 'Publish Quality Gate Result'
      inputs:
        pollingTimeoutSec: '300'